"""
Pydantic Models
"""

from .auth import (
    SignupRequest,
    LoginRequest,
    AuthResponse,
    UserResponse,
    UserProfile,
    UpdateProfileRequest,
    ChangePasswordRequest,
    ResetPasswordRequest,
    GoogleAuthRequest,
)
from .client import (
    ClientCreate,
    ClientUpdate,
    ClientResponse,
    ClientListResponse,
    INDUSTRIES,
    COMPANY_SIZES,
)
from .audit import (
    AuditCreate,
    AuditUpdate,
    AuditResponse,
    AuditListResponse,
    AuditWithClient,
    AuditProgress,
    AUDIT_STATUSES,
    AUDIT_TIERS,
    ANALYSIS_PHASES,
)
from .intake import (
    IntakeResponse,
    IntakeUpdate,
    IntakeComplete,
    IntakeWithAudit,
    QuestionnaireResponse,
    IntakeValidationResult,
)
from .recommendation import (
    # Core types
    OptionType,
    ConfidenceLevel,
    TimeHorizon,
    RiskProbability,
    FindingCategory,
    # Cost/Benefit models
    CostBreakdown,
    CostAnalysis,
    BenefitBreakdown,
    BenefitAnalysis,
    RiskItem,
    CRBAnalysis,
    # Three Options pattern
    OptionDetail,
    CustomSolutionDetail,
    RecommendationOptions,
    # Findings and Recommendations
    WhyItMatters,
    ValueSaved,
    ValueCreated,
    Finding,
    Recommendation,
    # Report structure
    Verdict,
    RoadmapItem,
    Roadmap,
    ValueSummary,
    ExecutiveSummary,
    MethodologyNotes,
    Report,
)
from .playbook import (
    TaskCRB,
    PlaybookTask,
    Week,
    PhaseCRBSummary,
    Phase,
    PersonalizationContext,
    Playbook,
    PlaybookProgress,
)
from .system_architecture import (
    NodeCRB,
    Position,
    ToolNode,
    Connection,
    AutomationNode,
    CostItem,
    CostBreakdown as ArchCostBreakdown,  # Renamed to avoid conflict
    CostComparison,
    SystemArchitecture,
)
from .industry_insights import (
    InsightCRB,
    AdoptionStat,
    OpportunityMap,
    SocialProof,
    IndustryInsights,
)
from .roi_calculator import (
    ROIInputs,
    CalculatorCRB,
    ROIResults,
    SavedScenario,
    ROICalculator,
)

__all__ = [
    # Auth
    "SignupRequest",
    "LoginRequest",
    "AuthResponse",
    "UserResponse",
    "UserProfile",
    "UpdateProfileRequest",
    "ChangePasswordRequest",
    "ResetPasswordRequest",
    "GoogleAuthRequest",
    # Client
    "ClientCreate",
    "ClientUpdate",
    "ClientResponse",
    "ClientListResponse",
    "INDUSTRIES",
    "COMPANY_SIZES",
    # Audit
    "AuditCreate",
    "AuditUpdate",
    "AuditResponse",
    "AuditListResponse",
    "AuditWithClient",
    "AuditProgress",
    "AUDIT_STATUSES",
    "AUDIT_TIERS",
    "ANALYSIS_PHASES",
    # Intake
    "IntakeResponse",
    "IntakeUpdate",
    "IntakeComplete",
    "IntakeWithAudit",
    "QuestionnaireResponse",
    "IntakeValidationResult",
    # Recommendation (Three Options pattern)
    "OptionType",
    "ConfidenceLevel",
    "TimeHorizon",
    "RiskProbability",
    "FindingCategory",
    "CostBreakdown",
    "CostAnalysis",
    "BenefitBreakdown",
    "BenefitAnalysis",
    "RiskItem",
    "CRBAnalysis",
    "OptionDetail",
    "CustomSolutionDetail",
    "RecommendationOptions",
    "WhyItMatters",
    "ValueSaved",
    "ValueCreated",
    "Finding",
    "Recommendation",
    "Verdict",
    "RoadmapItem",
    "Roadmap",
    "ValueSummary",
    "ExecutiveSummary",
    "MethodologyNotes",
    "Report",
    # Playbook
    "TaskCRB",
    "PlaybookTask",
    "Week",
    "PhaseCRBSummary",
    "Phase",
    "PersonalizationContext",
    "Playbook",
    "PlaybookProgress",
    # System Architecture
    "NodeCRB",
    "Position",
    "ToolNode",
    "Connection",
    "AutomationNode",
    "CostItem",
    "ArchCostBreakdown",
    "CostComparison",
    "SystemArchitecture",
    # Industry Insights
    "InsightCRB",
    "AdoptionStat",
    "OpportunityMap",
    "SocialProof",
    "IndustryInsights",
    # ROI Calculator
    "ROIInputs",
    "CalculatorCRB",
    "ROIResults",
    "SavedScenario",
    "ROICalculator",
]
