// ============================================================================
// Ecommerce-Focused Test Data
// Complete quiz answers + workshop deep-dive conversations for each sub-type
// ============================================================================

export interface IndustryTestData {
  description: string
  businessModel: string
  employeeRange: string
  employeeCount: number
  annualRevenue: string
  techStack: string[]
  painPoints: string[]
  biggestChallenge: string
  currentTools: string[]
  automationExperience: string
  aiBudget: string
  manualHoursWeekly: number
  // Full quiz answers matching backend schema
  quizAnswers: Record<string, string | string[] | number>
  // Voice interview conversation (5 Q&A pairs)
  interview: Array<{ role: string; content: string }>
  // Workshop deep-dive conversations per pain point (question → answer pairs)
  workshopDeepDives: Array<{
    painPoint: string
    conversation: Array<{ role: string; content: string }>
  }>
  confidenceScores: Record<string, { score: number; evidence: string[] }>
}

export const industryTestData: Record<string, IndustryTestData> = {
  // ── DTC Fashion & Apparel ──────────────────────────────────────────────
  'ecommerce-fashion': {
    description: 'Growing DTC fashion brand selling sustainable clothing through Shopify. Strong social media presence with expanding product catalog and international EU shipping.',
    businessModel: 'B2C E-commerce',
    employeeRange: '11-25',
    employeeCount: 16,
    annualRevenue: '€2M-5M',
    techStack: ['Shopify Plus', 'Klaviyo', 'Gorgias', 'Yotpo', 'Google Analytics 4'],
    painPoints: ['cart abandonment', 'support ticket overwhelm', 'inventory forecasting', 'returns processing'],
    biggestChallenge: 'Cart abandonment is at 72% and our recovery emails only convert 3% - we\'re leaving massive revenue on the table',
    currentTools: ['Shopify admin', 'Klaviyo for email', 'Excel for inventory planning', 'Gorgias for support tickets'],
    automationExperience: 'Basic email flows in Klaviyo, abandoned cart reminders, but personalization is minimal',
    aiBudget: '10000-25000',
    manualHoursWeekly: 30,
    quizAnswers: {
      industry: 'ecommerce',
      company_size: '11-25',
      employee_count: 16,
      annual_revenue: '2m_5m',
      ecommerce_platform: 'shopify_plus',
      monthly_order_volume: 3500,
      cart_abandonment_rate: '70_80',
      sales_channels: ['own_website', 'instagram_facebook_shop'],
      customer_service_volume: '100_300',
      fulfillment_method: 'hybrid',
      marketing_tools: ['klaviyo', 'meta_ads', 'google_ads'],
      return_rate: '20_30',
      inventory_management: 'spreadsheets',
      growth_priority: 'increase_revenue',
      ai_readiness: 'some',
      budget_timeline: 'next_quarter',
      current_tools: ['ecommerce_platform', 'email_marketing', 'helpdesk', 'reviews_ugc', 'analytics'],
      pain_points: ['cart abandonment', 'support ticket overwhelm', 'inventory forecasting', 'returns processing'],
      biggest_challenge: 'Cart abandonment is at 72% and our recovery emails only convert 3%',
      automation_experience: 'some',
      ai_budget: '10000-25000',
      manual_hours_weekly: 30,
      tech_comfort: 'comfortable',
    },
    interview: [
      { role: 'assistant', content: 'I\'ve done some research on Verde Sustainable Fashion. Tell me about your store — what do you sell and who\'s your typical customer?' },
      { role: 'user', content: 'We sell sustainable fashion — organic cotton basics, recycled polyester outerwear, and accessories. Our typical customer is a 28-35 year old woman in Germany or Netherlands who cares about sustainability but wants stylish clothes, not boring eco-wear.' },
      { role: 'assistant', content: 'Walk me through what happens from when a customer lands on your site to when they receive their order. Where do things break down?' },
      { role: 'user', content: 'They browse, add to cart, and then 72% of them abandon. We send one Klaviyo recovery email 24 hours later but only 3% convert. If they do buy, Shopify sends to our 3PL but we still manually check each order because of sizing issues. Gorgias gets 200+ tickets a day, 60% are WISMO — where is my order.' },
      { role: 'assistant', content: 'What\'s your biggest revenue leak right now?' },
      { role: 'user', content: 'Cart abandonment by far. At our AOV of €65 and 3,500 monthly orders, even recovering 5% more abandoned carts would be €50K+ per year. But we also lose on returns — 25% return rate, mostly because customers pick wrong sizes.' },
      { role: 'assistant', content: 'How do you handle customer support? What percentage of tickets could be automated?' },
      { role: 'user', content: 'We get 200+ support tickets a day through Gorgias. 60% are "where is my order?" which could easily be automated with tracking links. Another 20% are sizing questions we answer with a size chart link. So honestly 70-80% could be automated. Our 3 support agents are burned out.' },
      { role: 'assistant', content: 'If you could fix one thing about your operations before Black Friday, what would it be?' },
      { role: 'user', content: 'Inventory forecasting. We overstocked winter jackets by 40% last season — €80K tied up in dead inventory. And we ran out of our best-selling basics in week 2 of BFCM. We forecast with Excel and gut feel. We need something that actually looks at trends and sales velocity.' },
    ],
    workshopDeepDives: [
      {
        painPoint: 'cart abandonment',
        conversation: [
          { role: 'assistant', content: 'Let\'s talk about your cart abandonment. You mentioned 72% — walk me through what your current recovery process looks like.' },
          { role: 'user', content: 'We have one Klaviyo flow: 24 hours after abandonment, send an email reminding them. That\'s it. No SMS, no dynamic discounts, no multi-step sequence. It converts about 3% which is below industry average.' },
          { role: 'assistant', content: 'Have you tried anything else to address this — different tools, strategies, or sequences?' },
          { role: 'user', content: 'We tried adding a 10% discount in the email but it trained customers to abandon on purpose to get the discount. We considered SMS recovery through Klaviyo but haven\'t set it up. We also looked at exit-intent popups but our developer couldn\'t get them working with our Shopify theme.' },
          { role: 'assistant', content: 'Let\'s quantify the impact. At 3,500 orders/month with 72% abandonment and €65 AOV — what would improving recovery from 3% to 10% mean for you?' },
          { role: 'user', content: 'Let me think... 3,500 orders means roughly 12,500 total carts. 72% abandon = 9,000 abandoned carts. Going from 3% to 10% recovery = 630 extra orders per month × €65 = about €41K per month. That\'s almost €500K per year. Even half of that would be transformational for us.' },
          { role: 'assistant', content: 'What would the ideal cart recovery system look like for Verde?' },
          { role: 'user', content: 'A multi-touch sequence — email within 1 hour, SMS at 4 hours, personalized product recommendations at 24 hours, then a smart discount for high-value carts only at 48 hours. AI-powered so it learns which approach works for which customer segment. And it should integrate with our Shopify and Klaviyo stack seamlessly.' },
          { role: 'assistant', content: 'Who would need to approve implementing a system like this?' },
          { role: 'user', content: 'I\'m the founder so I make the call. My marketing manager would own the setup and our one developer would handle any integrations. Three of us total.' },
        ],
      },
      {
        painPoint: 'support ticket overwhelm',
        conversation: [
          { role: 'assistant', content: 'Tell me about your support ticket situation. You mentioned 200+ per day — how does your team handle that today?' },
          { role: 'user', content: 'Three agents in Gorgias. They manually triage every ticket. 60% are WISMO, 20% are sizing, 10% are returns, 10% are actual product issues. Each WISMO ticket takes 3 minutes to look up tracking and reply. That\'s 360 tickets × 3 min = 18 person-hours per day on copy-paste work.' },
          { role: 'assistant', content: 'Have you explored any automation for the WISMO and sizing tickets?' },
          { role: 'user', content: 'Gorgias has auto-responder rules but they\'re keyword-based and too dumb — they\'d send wrong tracking info or miss context. We tried their macros but agents still need to manually look up the order and paste the tracking number. We need something that actually understands the order status from Shopify.' },
          { role: 'assistant', content: 'What\'s the cost of this support load? Beyond the 18 hours/day on WISMO.' },
          { role: 'user', content: 'Three agents at €35K/year each = €105K. If 70% of tickets could be automated, that\'s potentially 2 agents worth of work. Plus response time suffers — our average first response is 4 hours. Customers get frustrated, leave bad reviews, and that impacts conversion. It\'s a vicious cycle.' },
          { role: 'assistant', content: 'What would ideal support automation look like for you?' },
          { role: 'user', content: 'An AI that connects to Shopify, reads order status, and auto-responds to WISMO tickets instantly. Same for sizing — pull up the product, check their order history for size patterns, and recommend confidently. Agents only handle returns and complex issues. Response time under 5 minutes for automated tickets.' },
          { role: 'assistant', content: 'Would your support team be open to AI handling most tickets, or would there be pushback?' },
          { role: 'user', content: 'They\'d love it. They hate WISMO tickets — it\'s soul-crushing work. They want to help with actual problems. My lead agent has been asking me to automate this for months.' },
        ],
      },
      {
        painPoint: 'inventory forecasting',
        conversation: [
          { role: 'assistant', content: 'You mentioned €80K in dead inventory from bad forecasting. Walk me through how you forecast demand today.' },
          { role: 'user', content: 'I look at last year\'s sales by category in a spreadsheet and add a growth factor. That\'s literally it. No seasonal adjustments beyond "winter = more jackets." No analysis of which specific SKUs are trending. I place orders with manufacturers 3 months in advance so mistakes are expensive.' },
          { role: 'assistant', content: 'What has that cost you beyond the dead inventory?' },
          { role: 'user', content: 'The €80K overstock was just winter jackets. Across all categories, I\'d estimate 15-20% of our inventory becomes dead stock annually — so roughly €150-200K tied up in products we eventually discount 50% or donate. And we also lost €30K in stockouts during BFCM when our best basics sold out in 3 days.' },
          { role: 'assistant', content: 'What data do you have that could feed better forecasting?' },
          { role: 'user', content: 'Shopify has all our sales data — 3 years of order history, product views, cart adds. Klaviyo has email engagement data showing what products people are clicking on. GA4 has search data showing what people are looking for. We have all this data but it just sits there.' },
          { role: 'assistant', content: 'What would solving this look like for you?' },
          { role: 'user', content: 'AI that looks at sales velocity, seasonal patterns, marketing calendar, and trend data to predict demand per SKU. Alerts when I need to reorder, warns when I\'m about to overstock. Ideally connects to Shopify so it sees real-time inventory levels. Even 50% better accuracy would save us €75K+ per year.' },
        ],
      },
      {
        painPoint: 'returns processing',
        conversation: [
          { role: 'assistant', content: 'Tell me about your returns — 25% rate with most being size-related. What does the return process look like?' },
          { role: 'user', content: 'Customer emails us or fills out a form. An agent creates a return label manually in ShipStation, emails it back. Package arrives, warehouse team inspects, restocks if possible or marks as damaged. Agent processes refund in Shopify. Total time: 15 minutes per return across multiple people.' },
          { role: 'assistant', content: 'How much are returns costing you annually?' },
          { role: 'user', content: 'With 875 returns/month at 25% rate: return shipping €5 + processing labor €8 + refund processing + 30% of returns are unsellable = roughly €15 per return. That\'s €13K/month or €156K/year. And that\'s before the revenue loss from the original sale.' },
          { role: 'assistant', content: 'What would reduce the return rate itself, not just make processing faster?' },
          { role: 'user', content: 'Better sizing tools. 70% of returns are "wrong size." If we had AI-powered size recommendations based on body measurements or past purchases, we could probably cut size-related returns in half. That alone would save us €55K/year in processing costs plus retain the revenue from those sales.' },
          { role: 'assistant', content: 'What\'s your ideal returns setup?' },
          { role: 'user', content: 'Self-service portal where customers initiate returns, auto-generated labels, automated refund on scan receipt, smart routing for exchange vs refund. And preventive — AI sizing recommendations to stop wrong-size orders from happening in the first place.' },
        ],
      },
    ],
    confidenceScores: {
      operations: { score: 90, evidence: ['Ticket volume quantified at 200+/day', 'Return processing time detailed at 15min each'] },
      technology: { score: 80, evidence: ['Modern Shopify Plus stack', 'Clear integration gaps between Klaviyo and Gorgias'] },
      financials: { score: 85, evidence: ['€80K dead inventory quantified', 'Cart abandonment rate and recovery rate specific'] },
      pain_points: { score: 90, evidence: ['Five distinct revenue leaks identified', 'Specific percentages and costs provided'] },
    },
  },

  // ── Health & Supplements ───────────────────────────────────────────────
  'ecommerce-supplements': {
    description: 'Online health supplements brand with subscription model. Sells vitamins, protein powders, and wellness products across DACH region with strong repeat purchase rate.',
    businessModel: 'B2C E-commerce / Subscription',
    employeeRange: '6-15',
    employeeCount: 11,
    annualRevenue: '€1M-3M',
    techStack: ['WooCommerce', 'Mailchimp', 'Zendesk', 'Google Ads', 'Recharge Subscriptions'],
    painPoints: ['subscription churn', 'regulatory compliance', 'customer education gaps', 'rising CAC'],
    biggestChallenge: 'We spend €45 to acquire a customer but average LTV is only €120 because churn is so high — people sign up for a month and cancel before month 3',
    currentTools: ['WooCommerce dashboard', 'Mailchimp for newsletters', 'Google Sheets for subscription tracking', 'WhatsApp for VIP customers'],
    automationExperience: 'Post-purchase email sequence and basic subscription renewal reminders. Nothing for churn prevention or win-back.',
    aiBudget: '5000-15000',
    manualHoursWeekly: 22,
    quizAnswers: {
      industry: 'ecommerce',
      company_size: '6-15',
      employee_count: 11,
      annual_revenue: '1m_3m',
      ecommerce_platform: 'woocommerce',
      monthly_order_volume: 1800,
      cart_abandonment_rate: '60_70',
      sales_channels: ['own_website'],
      customer_service_volume: '50_100',
      fulfillment_method: 'in_house',
      marketing_tools: ['mailchimp', 'google_ads'],
      return_rate: 'under_5',
      inventory_management: 'spreadsheets',
      growth_priority: 'customer_retention',
      ai_readiness: 'exploring',
      budget_timeline: 'next_quarter',
      current_tools: ['ecommerce_platform', 'email_marketing', 'helpdesk', 'analytics'],
      pain_points: ['subscription churn', 'regulatory compliance', 'customer education gaps', 'rising CAC'],
      biggest_challenge: 'LTV is only €120 vs €45 CAC because churn is 18% monthly',
      automation_experience: 'exploring',
      ai_budget: '5000-15000',
      manual_hours_weekly: 22,
      tech_comfort: 'comfortable',
    },
    interview: [
      { role: 'assistant', content: 'Tell me about PureVital — what do you sell and who\'s your typical customer?' },
      { role: 'user', content: 'We sell premium vitamins, protein powders, and wellness supplements online. Typical customer is a 30-45 year old health-conscious person in Germany or Austria who wants clean-label, third-party tested products. About 40% are subscribers.' },
      { role: 'assistant', content: 'Walk me through your customer journey from acquisition to retention.' },
      { role: 'user', content: 'They find us through Google Ads or Instagram, browse the shop, maybe buy a starter kit. We follow up with Mailchimp emails to convert them to subscription. Problem is 18% of subscribers cancel every month. Most say "I have too much product" because we can\'t adjust delivery frequency dynamically. By month 3, half are gone.' },
      { role: 'assistant', content: 'What\'s your biggest revenue leak right now?' },
      { role: 'user', content: 'Churn. We spend €45 to acquire a customer and LTV is only €120. If we could extend average subscription life from 3 months to 6 months, LTV would double. That\'s the difference between a viable business and a cash-burning machine. Google Ads CPC also went up 35% this year.' },
      { role: 'assistant', content: 'How do you handle customer questions about your products?' },
      { role: 'user', content: 'Zendesk handles 50-100 tickets per week. Lots of questions about dosage, interactions between supplements, and which products are right for them. Our support team copies from a FAQ doc but it\'s always outdated. We can\'t give personalized health advice — that\'s a regulatory minefield.' },
      { role: 'assistant', content: 'If you could fix one thing before next quarter, what would it be?' },
      { role: 'user', content: 'Churn prevention. If we could predict who\'s about to cancel and intervene — offer a pause, adjust frequency, suggest a different product — we could probably cut churn in half. That\'s worth more than any new acquisition channel.' },
    ],
    workshopDeepDives: [
      {
        painPoint: 'subscription churn',
        conversation: [
          { role: 'assistant', content: 'Let\'s dig into subscription churn. 18% monthly — what does that look like in real numbers?' },
          { role: 'user', content: 'We have about 700 active subscribers. 18% = ~126 cancellations per month. Average subscription is €35/month. That\'s €4,400/month in lost recurring revenue. And acquiring each of those customers cost us €45, so we\'re losing €5,670 in acquisition cost that never gets recovered.' },
          { role: 'assistant', content: 'Have you tried anything to reduce churn?' },
          { role: 'user', content: 'We added a cancellation survey — that\'s how we know "too much product" is the #1 reason. We tried manual outreach to at-risk subscribers but we can\'t identify them until they cancel. We also offered a 15% discount to stay but that just delays cancellation by one month and kills margin.' },
          { role: 'assistant', content: 'What data do you have about subscriber behavior before they cancel?' },
          { role: 'user', content: 'WooCommerce has order history. Recharge has subscription data — when they skip, when they change products. Mailchimp shows email engagement — open rates drop before cancellation. We can see the signals but have no way to act on them automatically. By the time we notice, they\'re already gone.' },
          { role: 'assistant', content: 'What would ideal churn prevention look like?' },
          { role: 'user', content: 'AI that monitors subscriber signals — declining email engagement, skipped deliveries, support tickets — and triggers personalized interventions. Auto-adjust delivery frequency before they cancel. Suggest product swaps. Offer a "subscription pause" at the right moment. And a smart win-back sequence for those who do cancel.' },
        ],
      },
      {
        painPoint: 'regulatory compliance',
        conversation: [
          { role: 'assistant', content: 'You mentioned compliance takes 2 weeks per SKU. Walk me through that process.' },
          { role: 'user', content: 'Every product description needs to comply with EU health claims regulation. We can\'t say "boosts immunity" without a registered claim. Our process: marketing writes copy, sends to our regulatory consultant, 3-5 rounds of back-and-forth, 2 weeks minimum. We have 60 SKUs and regulations change quarterly.' },
          { role: 'assistant', content: 'What\'s the cost of this compliance bottleneck?' },
          { role: 'user', content: 'The consultant charges €150/hour, about 3 hours per SKU review = €450/SKU. For all 60 products: €27K/year. Plus quarterly regulation updates require re-reviewing 10-15 products. And new product launches are delayed 2-3 weeks waiting for approved copy. That delay costs us €5-10K in missed early sales.' },
          { role: 'assistant', content: 'What would faster compliance look like?' },
          { role: 'user', content: 'AI that knows the EU health claims database and can flag non-compliant language instantly. Auto-suggest compliant alternatives. Pre-screen new product copy before it goes to our consultant so the review is faster. Even cutting the cycle from 2 weeks to 3 days would be massive.' },
        ],
      },
      {
        painPoint: 'customer education gaps',
        conversation: [
          { role: 'assistant', content: 'Tell me about the customer education challenge — how do customers decide what to buy?' },
          { role: 'user', content: 'They land on our site and see 60 products. No guided recommendation. Our product quiz is 3 questions and just filters by goal (energy, sleep, fitness). It doesn\'t consider what they\'re already taking, interactions, or dosage. Customers email us asking "what should I take?" and our agents aren\'t qualified to advise.' },
          { role: 'assistant', content: 'How does this affect conversion and retention?' },
          { role: 'user', content: 'Conversion rate for first-time visitors is only 1.8% — I think people leave because they don\'t know what to buy. And subscribers who were recommended wrong products churn faster. If someone buys a protein they don\'t like, they cancel everything. Our CSAT shows "didn\'t see results" as the #2 cancellation reason after "too much product."' },
          { role: 'assistant', content: 'What would an ideal product recommendation system look like?' },
          { role: 'user', content: 'An AI-powered quiz that asks about goals, current supplements, dietary restrictions, and health conditions. Recommends a personalized stack with dosage timing. Explains WHY each product was chosen. And adapts over time — if someone reports poor sleep, adjust their stack. Like a virtual nutritionist that stays compliant with EU regulations.' },
        ],
      },
      {
        painPoint: 'rising CAC',
        conversation: [
          { role: 'assistant', content: 'Your CAC went from what to where, and what\'s driving the increase?' },
          { role: 'user', content: 'CAC was €28 two years ago, now €45. Google Ads CPC up 35% this year. Meta CPM also up significantly. The supplements market is flooded — everyone from Huel to small TikTok brands. We can\'t outspend larger competitors on acquisition. Our organic is weak — no SEO strategy, no content marketing, blog posts once a month at best.' },
          { role: 'assistant', content: 'What are you doing to get more value from existing customers instead?' },
          { role: 'user', content: 'Honestly, not much. Our referral program is a manual discount code — maybe 5 referrals a month. No loyalty program. No cross-sell or upsell automation beyond a basic "you might also like" email. Our VIP customers who spend €800+/year get the same experience as someone who bought one €20 product. It\'s embarrassing.' },
          { role: 'assistant', content: 'What would reducing dependency on paid acquisition look like?' },
          { role: 'user', content: 'AI-generated SEO content about supplements — ingredient guides, comparison articles, "best for" pages. Automated referral program that\'s actually frictionless. Smart cross-sell recommendations based on what similar customers buy together. And a loyalty program with personalized rewards. Basically, make existing customers our growth engine instead of Google.' },
        ],
      },
    ],
    confidenceScores: {
      operations: { score: 85, evidence: ['Churn rate quantified at 18%', 'Support workflow described'] },
      technology: { score: 70, evidence: ['WooCommerce + Recharge stack identified', 'Manual tracking via Google Sheets'] },
      financials: { score: 90, evidence: ['CAC €45 and LTV €120 specified', 'CPC increase of 35% noted'] },
      pain_points: { score: 85, evidence: ['Churn root cause identified', 'Compliance bottleneck quantified at 2wk/SKU'] },
    },
  },

  // ── Home & Furniture ───────────────────────────────────────────────────
  'ecommerce-home': {
    description: 'Premium home furniture and decor brand selling through own webshop and marketplaces. High-AOV products requiring visual merchandising and configuration tools.',
    businessModel: 'B2C E-commerce / Omnichannel',
    employeeRange: '15-30',
    employeeCount: 22,
    annualRevenue: '€4M-8M',
    techStack: ['Magento 2', 'HubSpot', 'Freshdesk', 'Channable', 'Pinterest Ads'],
    painPoints: ['low conversion on high-AOV items', 'marketplace feed chaos', 'delivery logistics complaints', 'product photography costs'],
    biggestChallenge: 'Our average order is €850 but conversion rate is only 0.8% because customers can\'t visualize products in their space — they visit 6-7 times before buying or abandoning',
    currentTools: ['Magento admin', 'HubSpot CRM', 'Channable for marketplace feeds', 'Excel for delivery scheduling', 'WeTransfer for supplier catalogs'],
    automationExperience: 'HubSpot email sequences for abandoned carts. Channable automates some marketplace listings. Everything else is manual.',
    aiBudget: '15000-40000',
    manualHoursWeekly: 35,
    quizAnswers: {
      industry: 'ecommerce',
      company_size: '15-30',
      employee_count: 22,
      annual_revenue: '5m_plus',
      ecommerce_platform: 'magento',
      monthly_order_volume: 800,
      cart_abandonment_rate: '70_80',
      sales_channels: ['own_website', 'amazon', 'bol_com'],
      customer_service_volume: '50_100',
      fulfillment_method: 'hybrid',
      marketing_tools: ['meta_ads', 'google_ads'],
      return_rate: '10_20',
      inventory_management: 'dedicated_software',
      growth_priority: 'improve_margins',
      ai_readiness: 'exploring',
      budget_timeline: 'next_quarter',
      current_tools: ['ecommerce_platform', 'email_marketing', 'helpdesk', 'analytics', 'inventory_management'],
      pain_points: ['low conversion on high-AOV items', 'marketplace feed chaos', 'delivery logistics complaints', 'product photography costs'],
      biggest_challenge: 'Conversion rate is 0.8% on €850 AOV because customers can\'t visualize products in their space',
      automation_experience: 'some',
      ai_budget: '15000-40000',
      manual_hours_weekly: 35,
      tech_comfort: 'comfortable',
    },
    interview: [
      { role: 'assistant', content: 'Tell me about Nordic Living Interiors — what do you sell and through which channels?' },
      { role: 'user', content: 'Premium Scandinavian-inspired furniture and decor — sofas, dining tables, lighting, accessories. We sell through our Magento webshop, Amazon, bol.com, and Otto marketplace. Own webshop is 55% of revenue, marketplaces are growing fast. AOV is €850 on our own shop.' },
      { role: 'assistant', content: 'Walk me through your biggest operational challenge.' },
      { role: 'user', content: 'Conversion rate is only 0.8%. Customers browse our site 6-7 times over 3-4 weeks before buying — or giving up. They email photos of their living room asking "will this sofa match my wall?" and our team spends 2 hours per inquiry doing manual Photoshop mockups. We can\'t scale that.' },
      { role: 'assistant', content: 'How do you manage selling across 4 different channels?' },
      { role: 'user', content: 'Channable syncs some product data but pricing, stock, and descriptions need manual updates across channels. Last month we had wrong prices on bol.com for 3 days — lost €12K in margin. It\'s a full-time job for one person and they still make errors. Each marketplace has different image requirements, description formats, and attribute schemas.' },
      { role: 'assistant', content: 'What\'s happening with delivery and returns?' },
      { role: 'user', content: 'Delivery is our #1 complaint. We work with 8 suppliers — each ships direct to customer. We promise 2-week delivery but have zero real-time visibility into supplier stock or shipping status. Customers call us for updates and we literally phone the supplier. Returns are 15% and each costs €120 in logistics — furniture returns are brutal.' },
      { role: 'assistant', content: 'What would you fix first if you had a magic wand?' },
      { role: 'user', content: 'Product visualization. If customers could see our furniture in their space — AR or AI room mockups — I think conversion would double. That alone at €850 AOV would add millions in revenue. The technology exists, we just don\'t know how to implement it with our Magento setup.' },
    ],
    workshopDeepDives: [
      {
        painPoint: 'low conversion on high-AOV items',
        conversation: [
          { role: 'assistant', content: 'Let\'s dig into your 0.8% conversion rate. For high-AOV furniture, what does the customer decision journey look like?' },
          { role: 'user', content: 'Average 6-7 visits over 3-4 weeks. They browse categories, save favorites, come back, compare. Then they email us photos of their room asking if the product fits. 40% of these inquiries convert — but we can only handle 5-6 per day. The rest never get a response and probably buy from a competitor or give up.' },
          { role: 'assistant', content: 'What does handling those visual inquiries cost you today?' },
          { role: 'user', content: 'Our designer spends 2 hours per mockup in Photoshop. At 5-6/day and €40/hour, that\'s €400-480/day or roughly €9K/month. And wait time is 2-3 business days per request. By then, half the customers have moved on. We\'re paying a lot to convert slowly.' },
          { role: 'assistant', content: 'What would AI-powered visualization change for you?' },
          { role: 'user', content: 'If customers could upload a room photo and see our sofa in it instantly — no waiting, no emailing — I believe conversion would go from 0.8% to at least 1.5%. At our traffic of 100K monthly visitors, that\'s 700 extra orders × €850 = €595K per year in additional revenue. Plus we\'d eliminate the €9K/month in designer mockup costs.' },
          { role: 'assistant', content: 'Who needs to be involved in implementing this?' },
          { role: 'user', content: 'Me (CEO), our head of digital, and our Magento development agency. The agency charges €120/hour. We\'d need product photography in specific formats too — our photographer would need to shoot products against neutral backgrounds for AR/AI processing.' },
        ],
      },
      {
        painPoint: 'marketplace feed chaos',
        conversation: [
          { role: 'assistant', content: 'You lost €12K from a pricing error on bol.com. How does your multi-channel management work day-to-day?' },
          { role: 'user', content: 'One person manages all feeds through Channable. Product data goes Magento → Channable → marketplaces. But each marketplace needs different attributes, image sizes, category mappings. Channable handles the basic sync but pricing rules, promotions, and descriptions are all manual overrides. We have 300 products × 4 channels = 1,200 listings to maintain.' },
          { role: 'assistant', content: 'What goes wrong most often?' },
          { role: 'user', content: 'Price sync delays — our Magento price change takes 4-6 hours to propagate through Channable. During a sale event, that means we\'re selling at old prices on marketplaces. Also, Amazon requires different product titles than bol.com — our person rewrites 300 titles manually. And stock sync has a 2-hour lag, so we oversell about 3 times a month, leading to cancellations and penalties.' },
          { role: 'assistant', content: 'What does all of this cost you annually?' },
          { role: 'user', content: 'The pricing errors: maybe €30-40K/year in margin erosion. Overselling penalties from Amazon: €5K/year. One full-time person at €45K. Manual marketplace content creation: our copywriter spends 30% of their time rewriting listings, so another €12K. Total around €90-100K in direct costs, plus whatever revenue we lose from poor marketplace listings.' },
          { role: 'assistant', content: 'What would ideal multi-channel management look like?' },
          { role: 'user', content: 'AI that understands each marketplace\'s requirements and auto-generates optimized listings from our master product data. Real-time price and stock sync — not 4-6 hour delays. Auto-translate for German, Dutch, and English marketplaces. And smart pricing that adjusts based on competition and margin targets per channel.' },
        ],
      },
      {
        painPoint: 'delivery logistics complaints',
        conversation: [
          { role: 'assistant', content: 'Delivery complaints are your #1 issue. How does fulfillment work with 8 suppliers?' },
          { role: 'user', content: 'Most products ship directly from supplier to customer. We don\'t have a warehouse. When an order comes in, we email the supplier with the order details. They ship and (sometimes) send us a tracking number. Customer asks where their order is, we don\'t know, we call the supplier. Response time on these tickets is 1-2 days because we\'re waiting for suppliers.' },
          { role: 'assistant', content: 'How many delivery-related complaints do you get?' },
          { role: 'user', content: '35% of all support tickets are delivery-related. About 25 per week. Each takes an average of 20 minutes because of the back-and-forth with suppliers. That\'s 8+ hours per week just on delivery inquiries. And our NPS scores show delivery as the #1 reason for detractors — 30% of negative reviews mention delivery.' },
          { role: 'assistant', content: 'What would fix this?' },
          { role: 'user', content: 'Integration with our suppliers\' shipping systems so we have real-time tracking. Automated proactive updates to customers — "your order was shipped, here\'s tracking, expected delivery Thursday." AI-powered WISMO responses that check supplier status automatically. And honestly, a supplier scorecard so we can hold them accountable — right now we have no visibility into which suppliers are reliable.' },
        ],
      },
      {
        painPoint: 'product photography costs',
        conversation: [
          { role: 'assistant', content: 'You spend €60K/year on product photography. Break down that cost for me.' },
          { role: 'user', content: '€200 per SKU for standard white-background shots. €500-800 for lifestyle shots with staging. 300 products, seasonal refreshes twice a year. Each marketplace needs different image specs. New collections (50-80 products/year) need full shoots. Plus we need 360-degree views for our website which cost €300 per product. The photographer is booked 3-4 weeks out so launches get delayed.' },
          { role: 'assistant', content: 'How does photography quality affect your sales?' },
          { role: 'user', content: 'Directly. Products with lifestyle shots convert 3x better than white-background-only products. But we can only afford lifestyle shots for our top 30 products. The other 270 look generic and don\'t sell as well. We know better photos = more sales but the cost is prohibitive for the full catalog.' },
          { role: 'assistant', content: 'What would AI-generated product photography mean for your business?' },
          { role: 'user', content: 'If we could generate lifestyle shots from a single product photo — showing our lamp in a styled living room, or our table in a modern kitchen — we could have lifestyle imagery for all 300 products. At even €10 per AI-generated image vs €500+, we\'d save 95% on content creation. And we could test different styling to see what converts best. The ROI is enormous.' },
        ],
      },
    ],
    confidenceScores: {
      operations: { score: 90, evidence: ['2hr/inquiry for visual requests quantified', 'Delivery complaint root cause identified'] },
      technology: { score: 80, evidence: ['Multi-channel stack described', 'Marketplace feed issues specific'] },
      financials: { score: 95, evidence: ['AOV, conversion rate, photo costs, return costs all quantified', '€12K pricing error documented'] },
      pain_points: { score: 90, evidence: ['Five specific pain points with financial impact', 'Clear connection between visualization gaps and returns'] },
    },
  },

  // ── Food & Specialty Beverages ─────────────────────────────────────────
  'ecommerce-food': {
    description: 'Artisan food and specialty coffee brand with D2C subscription and wholesale. Temperature-sensitive products with strict freshness requirements and seasonal demand spikes.',
    businessModel: 'B2C + B2B E-commerce',
    employeeRange: '8-20',
    employeeCount: 14,
    annualRevenue: '€1.5M-4M',
    techStack: ['Shopify', 'Klaviyo', 'ShipStation', 'QuickBooks', 'Instagram Shopping'],
    painPoints: ['perishable inventory waste', 'seasonal demand unpredictability', 'wholesale order chaos', 'subscription frequency mismatch'],
    biggestChallenge: 'We throw away 12% of inventory due to expiration dates — that\'s €150K/year in waste. Our demand forecasting is basically guessing based on last year\'s numbers',
    currentTools: ['Shopify for D2C', 'WhatsApp groups for wholesale orders', 'Excel for batch tracking', 'ShipStation for shipping'],
    automationExperience: 'Klaviyo flows for reorder reminders based on purchase cycle. ShipStation auto-selects carriers. Wholesale is 100% manual via WhatsApp and phone.',
    aiBudget: '8000-20000',
    manualHoursWeekly: 28,
    quizAnswers: {
      industry: 'ecommerce',
      company_size: '8-20',
      employee_count: 14,
      annual_revenue: '1m_3m',
      ecommerce_platform: 'shopify',
      monthly_order_volume: 2200,
      cart_abandonment_rate: '50_60',
      sales_channels: ['own_website', 'wholesale', 'instagram_facebook_shop'],
      customer_service_volume: '20_50',
      fulfillment_method: 'in_house',
      marketing_tools: ['klaviyo', 'meta_ads'],
      return_rate: 'under_5',
      inventory_management: 'spreadsheets',
      growth_priority: 'improve_margins',
      ai_readiness: 'exploring',
      budget_timeline: 'this_month',
      current_tools: ['ecommerce_platform', 'email_marketing', 'shipping_fulfillment', 'analytics'],
      pain_points: ['perishable inventory waste', 'seasonal demand unpredictability', 'wholesale order chaos', 'subscription frequency mismatch'],
      biggest_challenge: '12% inventory waste from expiration — €150K/year lost',
      automation_experience: 'some',
      ai_budget: '8000-20000',
      manual_hours_weekly: 28,
      tech_comfort: 'comfortable',
    },
    interview: [
      { role: 'assistant', content: 'Tell me about Kaffee Handwerk — what products do you sell and how?' },
      { role: 'user', content: 'We\'re a specialty coffee roaster and artisan food brand. Single-origin coffees, custom blends, plus curated food items — chocolate, granola, honey. D2C through Shopify is 60% of revenue, wholesale to 80 cafes and restaurants is 40%. We also have a subscription box — about 400 subscribers getting monthly deliveries.' },
      { role: 'assistant', content: 'Walk me through your biggest operational headache.' },
      { role: 'user', content: 'Inventory waste. Coffee has a 6-week freshness window from roast date. We roast based on demand forecast but when orders don\'t match, we either run out of popular blends or waste specialty beans. 12% of inventory expires — €150K/year. Last month alone: €8K in expired single-origin Ethiopian that we over-roasted because a wholesale customer cancelled their order last minute.' },
      { role: 'assistant', content: 'How does the wholesale side work?' },
      { role: 'user', content: 'It\'s chaos. 80 cafe accounts order via WhatsApp messages. Someone manually types orders into Shopify. Last week we shipped 50 cases of the wrong blend from a copy-paste error. B2B accounts want NET30 invoicing but Shopify only does immediate payment, so we run parallel invoicing in QuickBooks that doesn\'t sync with anything.' },
      { role: 'assistant', content: 'What about seasonal demand — how do you plan for that?' },
      { role: 'user', content: 'Christmas is 40% of our annual revenue. We start production planning in August with zero data. We either overproduce gift sets and eat the loss — last year we had €25K in unsold Christmas boxes — or we sell out in week 2 and miss the rest of the season. There\'s no middle ground with our current approach.' },
      { role: 'assistant', content: 'If you could solve one thing before this year\'s holiday season, what would it be?' },
      { role: 'user', content: 'Demand forecasting tied to actual data. We have 3 years of Shopify sales history, wholesale order patterns, subscription data, even weather correlations for hot vs cold drink preferences. All this data exists but we don\'t use it. If AI could tell us "roast X kg of blend Y this week," we\'d cut waste in half and stop running out of best-sellers.' },
    ],
    workshopDeepDives: [
      {
        painPoint: 'perishable inventory waste',
        conversation: [
          { role: 'assistant', content: 'Let\'s quantify the inventory waste problem. 12% overall — does that vary by product type?' },
          { role: 'user', content: 'Single-origin specialty coffees waste the most — 20% because they\'re expensive, low-volume, and we can\'t predict demand. Mainstream blends waste 8% because demand is steadier. Food items waste 5% — longer shelf life. The 12% average hides that specialty coffees are bleeding money. Those are also our highest-margin products at 65% vs 45% for blends.' },
          { role: 'assistant', content: 'How do you decide what to roast each week?' },
          { role: 'user', content: 'I look at last week\'s sales and gut-feel adjust. Monday morning I decide the roast schedule for the week. Wholesale orders come in throughout the week so I\'m always reacting. Subscriptions are monthly so I know those volumes, but 60% of revenue is one-time D2C orders which are unpredictable. I spend 4 hours every Monday just on this planning.' },
          { role: 'assistant', content: 'What data exists that could improve forecasting?' },
          { role: 'user', content: '3 years of Shopify order data. Wholesale order history by account. Subscription renewal patterns. Seasonal trends — dark roasts spike in winter, cold brew in summer. Marketing calendar — when we send a newsletter, orders spike 40% for 2 days. Weather data correlates with coffee type preference. All in separate systems, none connected.' },
          { role: 'assistant', content: 'What would AI-powered forecasting save you?' },
          { role: 'user', content: 'If we cut waste from 12% to 5%, that\'s €90K/year saved on waste alone. If we also avoid stockouts on popular products — which cost us maybe €50K in missed sales last year — total impact is €140K. Plus I get 4 hours a week back from manual planning. The ROI on even a basic forecasting tool would be incredible.' },
        ],
      },
      {
        painPoint: 'wholesale order chaos',
        conversation: [
          { role: 'assistant', content: 'Walk me through a typical wholesale order from start to finish.' },
          { role: 'user', content: 'Cafe manager sends a WhatsApp message: "Need 10 bags of House Blend and 5 bags of Ethiopian." Our ops person copies this into Shopify as a manual draft order. Creates an invoice in QuickBooks for NET30. Emails confirmation. Prepares the order for our delivery driver. Total: 15-20 minutes per order. We process 50-60 wholesale orders per week.' },
          { role: 'assistant', content: 'What goes wrong in this process?' },
          { role: 'user', content: 'Copy-paste errors — wrong product, wrong quantity, wrong cafe address. Last week: 50 cases wrong blend shipped, €2K loss. QuickBooks and Shopify don\'t sync so accounts receivable is a mess — some invoices get lost, we\'re owed €15K in overdue payments we haven\'t chased. And WhatsApp history disappears so if there\'s a dispute, we have no paper trail.' },
          { role: 'assistant', content: 'What would the ideal wholesale system look like?' },
          { role: 'user', content: 'A B2B ordering portal where cafes log in, see their custom pricing, place orders with proper product selection. Auto-generates invoices in QuickBooks. Syncs to Shopify for fulfillment. Auto-reminders for overdue payments. AI-powered reorder suggestions based on each cafe\'s order history — "you usually order House Blend every 2 weeks, it\'s been 18 days."' },
        ],
      },
      {
        painPoint: 'seasonal demand unpredictability',
        conversation: [
          { role: 'assistant', content: 'Christmas is 40% of revenue — tell me about last year\'s planning and what went wrong.' },
          { role: 'user', content: 'In August we decided to produce 500 gift boxes at €45 cost each = €22.5K investment. Sold 380 in weeks 1-2, thought we\'d sell out. Then sales flatlined. Ended up with 120 unsold boxes (€5.4K waste) PLUS we ran out of our best-selling subscription blend during peak gift season because we diverted beans to gift boxes.' },
          { role: 'assistant', content: 'How does seasonal planning affect your production and cash flow?' },
          { role: 'user', content: 'We have to commit to bean purchases 2-3 months in advance because specialty green coffee has long lead times from origin. So August decisions lock in October-December costs. If we guess wrong, we either waste premium beans or can\'t fulfill demand. Christmas cash flow timing is also brutal — big expenses in September, revenue doesn\'t come until November-December.' },
          { role: 'assistant', content: 'What would better seasonal planning save you?' },
          { role: 'user', content: 'Last year\'s Christmas losses: €5.4K unsold gift boxes + €12K stockout on subscription blend + €3K in rush shipping for emergency bean orders = €20K. If AI could analyze 3 years of holiday data, early bird gift set pre-orders, and real-time sales velocity to adjust production weekly, we could probably cut that to under €5K in losses and add €15K in captured revenue.' },
        ],
      },
      {
        painPoint: 'subscription frequency mismatch',
        conversation: [
          { role: 'assistant', content: 'You have 400 subscribers but 30% pause or cancel because of "too much product." How does the subscription work?' },
          { role: 'user', content: 'Monthly delivery of 2 bags (500g each) at €28/month. Fixed frequency, fixed quantity. Customers can manually skip a month or cancel. We send a reminder email 5 days before each shipment. 30% of cancellations cite "too much coffee" — they\'re single-person households drinking the same amount but getting locked into a monthly cadence that\'s too fast.' },
          { role: 'assistant', content: 'What have you tried to address this?' },
          { role: 'user', content: 'We added a "skip" button in the reminder email. Helps a bit but people forget to skip and then get frustrated when another box arrives. We considered adding 6-week and 8-week frequency options but our Shopify subscription app (Recharge) makes that complicated. And we have no data on actual consumption patterns — we don\'t know who\'s drowning in coffee and who needs more.' },
          { role: 'assistant', content: 'What would smart subscription management look like?' },
          { role: 'user', content: 'AI that tracks each subscriber\'s reorder patterns (some people buy extra bags mid-cycle = they need more; some skip = they need less) and auto-adjusts delivery frequency. Proactive outreach before someone cancels: "We noticed you skipped the last two months — would you like to switch to every 6 weeks?" Smart product variety suggestions based on taste preferences. Turn churn into retention.' },
        ],
      },
    ],
    confidenceScores: {
      operations: { score: 95, evidence: ['12% waste rate quantified at €150K/year', 'Wholesale error example documented', 'Seasonal planning timeline specific'] },
      technology: { score: 75, evidence: ['Shopify + manual wholesale stack', 'No inventory management system'] },
      financials: { score: 90, evidence: ['Waste costs, seasonal revenue split, monthly losses all quantified'] },
      pain_points: { score: 95, evidence: ['Five distinct operational bottlenecks', 'Clear financial impact on each'] },
    },
  },

  // ── Beauty & Cosmetics ─────────────────────────────────────────────────
  'ecommerce-beauty': {
    description: 'Clean beauty brand selling skincare and cosmetics direct-to-consumer. Strong Instagram/TikTok presence, influencer-driven acquisition, expanding into EU markets.',
    businessModel: 'B2C E-commerce / DTC',
    employeeRange: '10-20',
    employeeCount: 13,
    annualRevenue: '€2M-6M',
    techStack: ['Shopify Plus', 'Klaviyo', 'Loyalty Lion', 'Okendo Reviews', 'Triple Whale'],
    painPoints: ['shade matching returns', 'influencer ROI tracking', 'product recommendation accuracy', 'email list fatigue'],
    biggestChallenge: 'Our return rate is 22% — mostly shade mismatches and "didn\'t suit my skin type." Each return costs us €18 in shipping plus the product is unsellable. That\'s €200K/year in losses',
    currentTools: ['Shopify Plus admin', 'Klaviyo for email/SMS', 'Google Sheets for influencer tracking', 'Notion for content calendar', 'Triple Whale for attribution'],
    automationExperience: 'Sophisticated Klaviyo flows (welcome, post-purchase, win-back, VIP). LoyaltyLion points program. But product recommendation and shade matching are completely manual.',
    aiBudget: '12000-30000',
    manualHoursWeekly: 25,
    quizAnswers: {
      industry: 'ecommerce',
      company_size: '10-20',
      employee_count: 13,
      annual_revenue: '2m_5m',
      ecommerce_platform: 'shopify_plus',
      monthly_order_volume: 4200,
      cart_abandonment_rate: '60_70',
      sales_channels: ['own_website', 'instagram_facebook_shop', 'tiktok_shop'],
      customer_service_volume: '100_300',
      fulfillment_method: '3pl',
      marketing_tools: ['klaviyo', 'meta_ads', 'tiktok_ads', 'influencer'],
      return_rate: '20_30',
      inventory_management: 'platform_builtin',
      growth_priority: 'improve_margins',
      ai_readiness: 'some',
      budget_timeline: 'next_quarter',
      current_tools: ['ecommerce_platform', 'email_marketing', 'reviews_ugc', 'analytics', 'helpdesk'],
      pain_points: ['shade matching returns', 'influencer ROI tracking', 'product recommendation accuracy', 'email list fatigue'],
      biggest_challenge: '22% return rate from shade/skin type mismatches — €200K/year in losses',
      automation_experience: 'some',
      ai_budget: '12000-30000',
      manual_hours_weekly: 25,
      tech_comfort: 'comfortable',
    },
    interview: [
      { role: 'assistant', content: 'Tell me about Glow Republic — what makes your brand different?' },
      { role: 'user', content: 'We\'re a clean beauty brand — all natural ingredients, cruelty-free, EU-certified. We sell 120 SKUs across skincare, makeup, and body care. Our audience is 22-38 year old women who discover us on Instagram and TikTok. We work with 40 influencers. Revenue is €3.5M this year, growing 40% YoY.' },
      { role: 'assistant', content: 'What\'s the biggest problem costing you money right now?' },
      { role: 'user', content: '22% return rate. Our foundations and concealers have 12 shades each. Customers guess their shade, get it wrong, return it. Product is unsellable after return. €18 per return in shipping and handling. 4,200 orders/month × 22% = 924 returns × €18 = €16.6K/month in return costs alone. Plus we lose the product cost. Total: about €200K/year.' },
      { role: 'assistant', content: 'How do customers currently find their shade?' },
      { role: 'user', content: 'They message us on Instagram 80 times a day asking "which shade am I?" Our team says "send a selfie" and manually matches — takes 10 minutes per person and we still get it wrong 30% of the time because lighting varies. Our website has a shade chart image but nobody reads it. Competitors are launching AI skin analysis from photos and we\'re falling behind.' },
      { role: 'assistant', content: 'What about your influencer program — how does that work?' },
      { role: 'user', content: 'We give 40 influencers unique discount codes and free products. They post content, followers buy using their code. Problem: only 30% of sales from influenced customers use the code. People screenshot, share with friends, or buy weeks later without the code. We have no idea which influencers actually drive profit vs just cost us product. Triple Whale helps with attribution but it\'s not reliable enough.' },
      { role: 'assistant', content: 'If you could fix one thing, what would have the biggest impact?' },
      { role: 'user', content: 'AI shade matching. If customers could upload a selfie and get matched to their perfect shade with 90%+ accuracy, return rates would plummet. Even going from 22% to 12% saves €100K/year. Plus it\'s a conversion tool — customers who are confident in their shade buy more. And it\'s a competitive moat — no other clean beauty brand in EU has this yet.' },
    ],
    workshopDeepDives: [
      {
        painPoint: 'shade matching returns',
        conversation: [
          { role: 'assistant', content: 'Let\'s break down the shade matching problem. Of your 22% return rate, how much is shade-related vs other reasons?' },
          { role: 'user', content: '65% of returns are shade/color mismatches. 20% are "didn\'t suit my skin type" for skincare. 15% are other (wrong item, damaged, changed mind). So shade matching alone causes about 14% return rate. That\'s ~600 returns/month at €18 processing + ~€12 average product cost that\'s unsellable = €18K/month or €216K/year just from shade issues.' },
          { role: 'assistant', content: 'How do the 80 daily Instagram shade inquiries work right now?' },
          { role: 'user', content: 'Customer DMs us a selfie or asks "I\'m NC25 in MAC, what\'s my shade in Glow Republic?" Agent opens our shade comparison chart, eyeballs the match, responds. 10 minutes per inquiry. We handle maybe 40-50 of the 80 requests per day — the rest never get answered. Those unanswered requests are probably lost sales. At €45 AOV for foundation, that\'s 30+ lost sales per day.' },
          { role: 'assistant', content: 'What have you tried to improve the shade selection experience?' },
          { role: 'user', content: 'A static shade quiz on our website — 4 questions about undertone, skin depth, etc. It narrows down to 3-4 shades but customers still can\'t tell the difference between "Warm Sand" and "Golden Beige" on their screen. We also tried shade comparison swatches in our product photography but arm swatches don\'t translate to face shades. The quiz converts at 15% — meaning 85% abandon it.' },
          { role: 'assistant', content: 'What would AI shade matching need to do to solve this?' },
          { role: 'user', content: 'Upload a selfie → AI analyzes skin tone, undertone, and lighting conditions → recommends specific shade with 90%+ confidence → shows an AR preview of how the product looks on the customer\'s actual face. Integrate into PDP so it\'s part of the buying flow, not a separate step. Cross-reference with MAC/Fenty/NARS shade equivalents so customers who know their shade in another brand can instant-match.' },
        ],
      },
      {
        painPoint: 'influencer ROI tracking',
        conversation: [
          { role: 'assistant', content: 'You work with 40 influencers. What\'s your total investment and how do you measure return?' },
          { role: 'user', content: 'Each influencer gets €200-500 in free product per month plus 15% commission on code-tracked sales. Top 5 get a €500/month retainer. Total spend: about €8K/month in product + €3K in retainers + commissions. We can track code-attributed sales — about €25K/month. But we estimate total influenced revenue is 2-3x that based on traffic spikes after posts.' },
          { role: 'assistant', content: 'What specific tracking gaps exist?' },
          { role: 'user', content: 'Code usage is only 30%. Someone sees an influencer post, goes to our site a week later and buys without the code — we can\'t attribute it. Influencer posts drive brand awareness but we can\'t measure "this micro-influencer\'s audience buys more, this mega-influencer\'s audience just browses." UTM links help but only for link-in-bio, not Stories or TikTok. We have 40 influencers and genuinely don\'t know which 10 are profitable and which 10 we should drop.' },
          { role: 'assistant', content: 'What would better attribution mean financially?' },
          { role: 'user', content: 'If we could identify the bottom 10 underperforming influencers and reallocate their budget (€2K/month) to proven performers, that\'s probably a 30-40% improvement in influencer-driven revenue. On our current base, that\'s €7-10K/month in additional revenue. Plus we\'d stop wasting €2K/month on influencers who don\'t convert — €24K/year saved.' },
          { role: 'assistant', content: 'What tools or approach would solve this?' },
          { role: 'user', content: 'AI attribution that goes beyond discount codes — tracks post-view to site-visit to purchase correlations. Looks at which influencer\'s audience has the highest LTV, not just first-purchase value. Auto-generates performance reports per influencer. Suggests optimal product seeding based on audience demographics. And predictive — tells us which NEW influencers to approach based on audience overlap with our best customers.' },
        ],
      },
      {
        painPoint: 'product recommendation accuracy',
        conversation: [
          { role: 'assistant', content: 'Tell me about how customers discover the right products for their skin today.' },
          { role: 'user', content: 'Our skincare quiz is 5 static questions: skin type, concerns, age range, routine complexity, sensitivity. It maps to one of 8 "skin profiles" and recommends the same 3 products to everyone in that profile. So all 25-35 year olds with oily skin and acne concerns get the exact same recommendation regardless of climate, lifestyle, current products, or budget.' },
          { role: 'assistant', content: 'How does recommendation quality affect conversion and retention?' },
          { role: 'user', content: 'Quiz completion to purchase conversion is only 18%. Those who buy recommended products have a 2.1x repeat purchase rate vs general buyers — so recommendations work when they\'re right. But "didn\'t see results" is the #2 reason for subscription cancellation. I think we\'re recommending wrong products to about 30% of quiz takers, losing those customers permanently.' },
          { role: 'assistant', content: 'What would an ideal recommendation engine look like?' },
          { role: 'user', content: 'AI skin analysis from a selfie — detects skin type, concerns (acne, dark spots, wrinkles, dehydration), and environmental factors. Considers what they\'re currently using and what hasn\'t worked. Builds a personalized routine with morning/evening steps and explains why each product was chosen. Updates recommendations based on progress photos over time — "your dark spots have faded, let\'s adjust your routine." Basically a dermatologist in an app.' },
        ],
      },
      {
        painPoint: 'email list fatigue',
        conversation: [
          { role: 'assistant', content: 'Your open rates dropped from 45% to 22%. What changed?' },
          { role: 'user', content: 'We launch new products monthly and blast the entire list every time. Same email to everyone regardless of skin type, purchase history, or interests. Someone who only buys lipstick gets skincare launch emails. We also send 2-3 promotional emails per week on top of automated flows. Unsubscribe rate doubled in 6 months — from 0.3% to 0.6% per campaign.' },
          { role: 'assistant', content: 'What\'s the revenue impact of this declining engagement?' },
          { role: 'user', content: 'Email drives 30% of our revenue — about €90K/month. Open rate dropping from 45% to 22% means roughly half the eyeballs. Click rates fell proportionally. We estimate we\'re losing €15-20K/month in email-driven revenue compared to a year ago. And every unsubscribe is a customer we can never email again — that\'s permanent damage to a €90K/month channel.' },
          { role: 'assistant', content: 'What would smart email personalization look like?' },
          { role: 'user', content: 'AI-driven segmentation based on purchase history, browsing behavior, skin profile, and engagement patterns. Send lipstick launches to lipstick buyers, skincare launches to skincare buyers. Personalize product recommendations in every email. Optimal send frequency per subscriber — some want 3x/week, others 1x/month. Re-engagement before they unsubscribe, not after. Basically what Klaviyo promises but doesn\'t deliver out of the box.' },
        ],
      },
    ],
    confidenceScores: {
      operations: { score: 90, evidence: ['80 daily shade-match requests quantified', 'Return rate and cost per return specific'] },
      technology: { score: 85, evidence: ['Advanced Shopify Plus stack', 'Clear gaps in AI/ML capabilities'] },
      financials: { score: 90, evidence: ['€200K/year return losses', 'Email engagement decline quantified'] },
      pain_points: { score: 95, evidence: ['Five specific pain points with clear AI solutions', 'Competitive pressure from AI-enabled rivals'] },
    },
  },

  // ── B2B Industrial Parts ───────────────────────────────────────────────
  'ecommerce-b2b': {
    description: 'B2B e-commerce platform selling industrial parts and MRO supplies. Handles complex quoting, bulk orders, and custom pricing tiers for 500+ business accounts.',
    businessModel: 'B2B E-commerce',
    employeeRange: '15-30',
    employeeCount: 24,
    annualRevenue: '€3M-8M',
    techStack: ['Custom React app', 'PostgreSQL', 'Stripe Connect', 'Algolia', 'Segment'],
    painPoints: ['supplier onboarding bottleneck', 'catalog data quality', 'quote response delays', 'duplicate listing chaos'],
    biggestChallenge: 'Onboarding a new supplier takes 3 weeks of back-and-forth to get their catalog formatted correctly - we lose 40% of interested suppliers before they go live',
    currentTools: ['Custom admin panel', 'Intercom for support', 'Notion for supplier docs', 'Google Sheets for pricing'],
    automationExperience: 'Basic email notifications on orders, but supplier onboarding and catalog management is fully manual',
    aiBudget: '20000-50000',
    manualHoursWeekly: 40,
    quizAnswers: {
      industry: 'ecommerce',
      company_size: '15-30',
      employee_count: 24,
      annual_revenue: '5m_plus',
      ecommerce_platform: 'custom',
      monthly_order_volume: 1200,
      cart_abandonment_rate: '50_60',
      sales_channels: ['own_website'],
      customer_service_volume: '100_300',
      fulfillment_method: 'hybrid',
      marketing_tools: ['google_ads'],
      return_rate: '5_10',
      inventory_management: 'dedicated_software',
      growth_priority: 'scale_operations',
      ai_readiness: 'some',
      budget_timeline: 'next_quarter',
      current_tools: ['ecommerce_platform', 'helpdesk', 'analytics', 'inventory_management'],
      pain_points: ['supplier onboarding bottleneck', 'catalog data quality', 'quote response delays', 'duplicate listing chaos'],
      biggest_challenge: 'Supplier onboarding takes 3 weeks — we lose 40% of interested suppliers',
      automation_experience: 'some',
      ai_budget: '20000-50000',
      manual_hours_weekly: 40,
      tech_comfort: 'very_comfortable',
    },
    interview: [
      { role: 'assistant', content: 'Tell me about PartsBridge — how does your marketplace work?' },
      { role: 'user', content: 'We connect industrial parts buyers with 200+ suppliers. Think of us as a vertical Amazon for bearings, fasteners, hydraulics, and MRO supplies. Buyers search our catalog, request quotes from multiple suppliers, and purchase. We handle the marketplace logistics — payments, dispute resolution, and catalog management.' },
      { role: 'assistant', content: 'Walk me through your biggest operational bottleneck.' },
      { role: 'user', content: 'Supplier onboarding. Each supplier sends their catalog in a different format — PDFs, Excel files, XML feeds, even handwritten lists. We have to normalize all of this into our schema. 3 weeks of back-and-forth per supplier. We get 50 supplier applications per week but our team can only onboard 8. We lose 40% of interested suppliers because they give up waiting.' },
      { role: 'assistant', content: 'What\'s the data quality challenge on the catalog side?' },
      { role: 'user', content: 'The same SKF 6205 bearing appears under 15 different names from different suppliers. No standard part numbers across suppliers. Duplicate listings confuse buyers — they can\'t tell if it\'s the same part at different prices or different parts. Our team manually deduplicates 200-300 listings per week. Miss one and we get returns, complaints, and lost trust.' },
      { role: 'assistant', content: 'How does quoting work and where does it break down?' },
      { role: 'user', content: 'Buyer requests a quote for, say, 500 units of a specific bearing. We send the RFQ to 10 matching suppliers. Only 3 respond within 24 hours. We spend hours calling the other 7. Buyer is waiting, gets frustrated, goes to Amazon Business instead. Our quote-to-order conversion is only 35% and slow response time is the #1 reason buyers cite.' },
      { role: 'assistant', content: 'What would you prioritize fixing?' },
      { role: 'user', content: 'Catalog normalization with AI. If we could auto-process any supplier catalog format into our schema in minutes instead of weeks, we\'d 5x our supplier onboarding rate. More suppliers = more products = more buyers = network effects. That\'s the growth flywheel we need to unlock.' },
    ],
    workshopDeepDives: [
      {
        painPoint: 'supplier onboarding bottleneck',
        conversation: [
          { role: 'assistant', content: 'Walk me through the supplier onboarding process step by step.' },
          { role: 'user', content: 'Supplier applies on our site. Our team reviews their catalog submission — usually a PDF or Excel file with 500-5000 products. We map their columns to our schema (part number, description, specs, price, stock, lead time). Every supplier has different column names and formats. Then we upload, validate, fix errors, go back to supplier for clarifications. 3 weeks average, 10-15 hours of analyst time per supplier.' },
          { role: 'assistant', content: 'What have you tried to speed this up?' },
          { role: 'user', content: 'We built CSV templates and asked suppliers to fill them in. Maybe 20% of suppliers can actually do this — most don\'t have the data in that format. We tried hiring more catalog analysts but they take 3 months to train and quality is inconsistent. We looked at Akeneo PIM but it still requires manual mapping — just moves the problem into a fancier tool.' },
          { role: 'assistant', content: 'What\'s the business cost of slow onboarding?' },
          { role: 'user', content: 'We lose 40% of applicant suppliers = about 20 suppliers/week that would have joined. Each active supplier generates an average of €2K/month in GMV with 15% take rate = €300/month revenue. So each lost supplier = €3,600/year in lost revenue. 20/week × 52 weeks × €3,600 = over €3.7M in annual revenue we\'re leaving on the table. Even capturing 25% of that by doubling onboarding capacity would add nearly €1M.' },
          { role: 'assistant', content: 'What would AI-powered catalog processing look like?' },
          { role: 'user', content: 'Upload any format — PDF, Excel, XML, images of paper catalogs. AI extracts product data, maps to our schema, identifies the correct standardized part number, fills in missing specs from manufacturer databases, flags confidence levels. Analyst reviews and approves instead of doing the data entry. Go from 15 hours to 2 hours per supplier. From 8 suppliers/week to 40+.' },
        ],
      },
      {
        painPoint: 'catalog data quality',
        conversation: [
          { role: 'assistant', content: 'Tell me about the duplicate listing problem in detail.' },
          { role: 'user', content: 'One SKF 6205-2RS bearing might appear as: "SKF 6205-2RS", "6205-2RS/C3", "SKF Explorer 6205", "6205 2RS1" from different suppliers. Same product, different names, different detail levels. We have 120,000 active listings and estimate 15-20% are duplicates or near-duplicates. That\'s 18,000-24,000 problem listings.' },
          { role: 'assistant', content: 'What does deduplication look like today?' },
          { role: 'user', content: 'Two analysts manually review flagged listings. They compare part numbers, specifications, and images. 200-300 listings per week. Each takes 5-10 minutes to verify. That\'s 25-50 hours per week on deduplication. And we\'re falling behind — new supplier catalogs add faster than we can clean.' },
          { role: 'assistant', content: 'What does poor data quality cost your marketplace?' },
          { role: 'user', content: 'Buyer confusion → wrong purchases → 8% return rate on mismatched parts. Each return costs €25 in B2B logistics. Search quality suffers — buyers can\'t find the right part → they leave → we lose the transaction. Our buyer NPS shows "hard to find the right part" as the #1 complaint. I estimate poor data quality costs us 10-15% in lost GMV — that\'s €400-600K/year on our current volume.' },
          { role: 'assistant', content: 'What would solving this look like?' },
          { role: 'user', content: 'AI entity resolution — match incoming product listings to our canonical product database using part numbers, specifications, images, and manufacturer data. Auto-merge duplicates. Flag potential matches for analyst review. Build a global parts knowledge graph so we can instantly recognize any part variant. This would also enable "compatible alternatives" recommendations which buyers constantly ask for.' },
        ],
      },
      {
        painPoint: 'quote response delays',
        conversation: [
          { role: 'assistant', content: 'Only 3 of 10 suppliers respond to RFQs within 24 hours. Why so slow?' },
          { role: 'user', content: 'Our RFQ goes to supplier\'s email. Their sales person has to log in to our portal, check stock, calculate pricing for bulk quantity (which might differ from catalog price), and submit a quote. Many suppliers are small shops with 5-10 people — the owner is also the sales person, warehouse manager, and machinist. Our RFQ is one of 50 emails they get that day.' },
          { role: 'assistant', content: 'How does this affect buyer experience and your revenue?' },
          { role: 'user', content: 'Buyers want quotes within hours, not days. Our quote-to-order conversion is 35%. Competitors like Amazon Business give instant pricing. When we take 3 days to aggregate quotes, 40% of buyers have already purchased elsewhere. On an average RFQ of €2K, losing 40% of €2K × 300 monthly RFQs = €240K/month in lost orders. Even if half would never convert, that\'s €120K/month.' },
          { role: 'assistant', content: 'What would speed up the quoting process?' },
          { role: 'user', content: 'AI-powered instant quotes based on historical pricing data, supplier cost patterns, and market rates. For standard parts with known pricing, give the buyer an instant estimate. For custom or bulk orders, auto-contact only the top 3 most likely suppliers (based on their response rates and inventory) instead of blasting 10. And auto-follow-up with non-responsive suppliers after 4 hours, escalating to phone if needed.' },
        ],
      },
      {
        painPoint: 'duplicate listing chaos',
        conversation: [
          { role: 'assistant', content: 'Beyond the deduplication effort, how do duplicate listings affect the buyer journey?' },
          { role: 'user', content: 'A buyer searches "6205 bearing" and gets 45 results. Same part from 12 suppliers, plus variants, plus duplicates. No way to compare apples-to-apples. They can\'t tell if the €8 listing and the €12 listing are the same quality from different suppliers or different products entirely. So they either email our support (200+ comparison requests/month) or just go to a supplier they already know — defeating our marketplace purpose.' },
          { role: 'assistant', content: 'What data do you have that could power better matching?' },
          { role: 'user', content: 'Manufacturer part number databases (some are public, some we\'ve scraped). Technical specification sheets. Historical purchase data showing which listings buyers consider equivalent. Return data showing when a buyer received the "wrong" part. Supplier quality ratings from past transactions. All of this is underutilized.' },
          { role: 'assistant', content: 'What would the ideal search and matching experience look like?' },
          { role: 'user', content: 'Buyer searches "6205 bearing" → sees ONE canonical product page with all supplier options side by side (price, lead time, MOQ, supplier rating). Can filter by spec variants (sealed, shielded, clearance class). "Compatible alternatives" section shows equivalent parts from other manufacturers. Natural language search — "I need a bearing for a 25mm shaft, 52mm housing, waterproof." That\'s the holy grail.' },
        ],
      },
    ],
    confidenceScores: {
      operations: { score: 90, evidence: ['Supplier onboarding time quantified at 3 weeks', 'Quote response rate 3/10 documented'] },
      technology: { score: 75, evidence: ['Custom stack described', 'Search limitations acknowledged'] },
      financials: { score: 85, evidence: ['40% supplier drop-off quantified', 'Revenue impact of poor matching implied'] },
      pain_points: { score: 95, evidence: ['Data quality issues across catalog', 'Clear scaling bottleneck'] },
    },
  },
}

// Map old industry keys to new ecommerce sub-types for backwards compatibility
export const INDUSTRY_TO_SUBTYPE: Record<string, string> = {
  'ecommerce': 'ecommerce-fashion',
  'dental': 'ecommerce-supplements',
  'b2b-platforms': 'ecommerce-b2b',
  'professional-services': 'ecommerce-home',
}

// Model strategies — only models we actually support
export const MODEL_STRATEGIES = [
  { id: 'anthropic_quick', label: 'Claude Sonnet (Quick)', description: 'Fast, cost-effective — Sonnet for generation' },
  { id: 'anthropic_full', label: 'Claude Opus 4.5 (Full)', description: 'Premium quality — Opus for all generation' },
  { id: 'hybrid', label: 'Hybrid (Recommended)', description: 'Haiku extraction → Sonnet generation → Opus analysis' },
] as const

// Ecommerce-focused test companies
export const TEST_COMPANIES = [
  { name: 'Verde Sustainable Fashion', industry: 'ecommerce', subtype: 'ecommerce-fashion', website: 'verdesustainable.com' },
  { name: 'PureVital Supplements', industry: 'ecommerce', subtype: 'ecommerce-supplements', website: 'purevital.de' },
  { name: 'Nordic Living Interiors', industry: 'ecommerce', subtype: 'ecommerce-home', website: 'nordicliving.eu' },
  { name: 'Kaffee Handwerk', industry: 'ecommerce', subtype: 'ecommerce-food', website: 'kaffeehandwerk.de' },
  { name: 'Glow Republic Beauty', industry: 'ecommerce', subtype: 'ecommerce-beauty', website: 'glowrepublic.com' },
  { name: 'PartsBridge Industrial', industry: 'ecommerce', subtype: 'ecommerce-b2b', website: 'partsbridge.io' },
] as const
